// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: agent/private/display/v1/service.proto

package displayv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_agent_private_display_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_private_display_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_agent_private_display_v1_service_proto_rawDescGZIP(), []int{0}
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Displays      []*Display             `protobuf:"bytes,1,rep,name=displays,proto3" json:"displays,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_agent_private_display_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_private_display_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_agent_private_display_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListResponse) GetDisplays() []*Display {
	if x != nil {
		return x.Displays
	}
	return nil
}

type Display struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Enable        bool                   `protobuf:"varint,3,opt,name=enable,proto3" json:"enable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Display) Reset() {
	*x = Display{}
	mi := &file_agent_private_display_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Display) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Display) ProtoMessage() {}

func (x *Display) ProtoReflect() protoreflect.Message {
	mi := &file_agent_private_display_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Display.ProtoReflect.Descriptor instead.
func (*Display) Descriptor() ([]byte, []int) {
	return file_agent_private_display_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *Display) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Display) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Display) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

type SetEnabledRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // ID или имя монитора
	Enable        bool                   `protobuf:"varint,2,opt,name=enable,proto3" json:"enable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetEnabledRequest) Reset() {
	*x = SetEnabledRequest{}
	mi := &file_agent_private_display_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetEnabledRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEnabledRequest) ProtoMessage() {}

func (x *SetEnabledRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_private_display_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEnabledRequest.ProtoReflect.Descriptor instead.
func (*SetEnabledRequest) Descriptor() ([]byte, []int) {
	return file_agent_private_display_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *SetEnabledRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetEnabledRequest) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

type SetEnabledResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetEnabledResponse) Reset() {
	*x = SetEnabledResponse{}
	mi := &file_agent_private_display_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetEnabledResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEnabledResponse) ProtoMessage() {}

func (x *SetEnabledResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_private_display_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEnabledResponse.ProtoReflect.Descriptor instead.
func (*SetEnabledResponse) Descriptor() ([]byte, []int) {
	return file_agent_private_display_v1_service_proto_rawDescGZIP(), []int{4}
}

var File_agent_private_display_v1_service_proto protoreflect.FileDescriptor

const file_agent_private_display_v1_service_proto_rawDesc = "" +
	"\n" +
	"&agent/private/display/v1/service.proto\x12\x18agent.private.display.v1\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\r\n" +
	"\vListRequest\"M\n" +
	"\fListResponse\x12=\n" +
	"\bdisplays\x18\x01 \x03(\v2!.agent.private.display.v1.DisplayR\bdisplays\"E\n" +
	"\aDisplay\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06enable\x18\x03 \x01(\bR\x06enable\";\n" +
	"\x11SetEnabledRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06enable\x18\x02 \x01(\bR\x06enable\"\x14\n" +
	"\x12SetEnabledResponse2\xe8\x02\n" +
	"\x15PrivateDisplayService\x12\x86\x01\n" +
	"\x04List\x12%.agent.private.display.v1.ListRequest\x1a&.agent.private.display.v1.ListResponse\"/\x92A\x18\n" +
	"\aDisplay\x1a\rlist displays\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/displays\x12\xae\x01\n" +
	"\n" +
	"SetEnabled\x12+.agent.private.display.v1.SetEnabledRequest\x1a,.agent.private.display.v1.SetEnabledResponse\"E\x92A \n" +
	"\aDisplay\x1a\x15Switch display enable\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/displays/set-enable\x1a\x15\x92A\x12\n" +
	"\aDisplay\x12\aDisplayB\x88\x02\x92A!\x12\x1f\n" +
	"\aDisplay\x12\x0fDisplay control2\x031.0\n" +
	"\x1ccom.agent.private.display.v1B\fServiceProtoP\x01Z1wallet/pkg/api/agent/private/display/v1;displayv1\xa2\x02\x03APD\xaa\x02\x18Agent.Private.Display.V1\xca\x02\x19Agent\\Private_\\Display\\V1\xe2\x02%Agent\\Private_\\Display\\V1\\GPBMetadata\xea\x02\x1bAgent::Private::Display::V1b\x06proto3"

var (
	file_agent_private_display_v1_service_proto_rawDescOnce sync.Once
	file_agent_private_display_v1_service_proto_rawDescData []byte
)

func file_agent_private_display_v1_service_proto_rawDescGZIP() []byte {
	file_agent_private_display_v1_service_proto_rawDescOnce.Do(func() {
		file_agent_private_display_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_private_display_v1_service_proto_rawDesc), len(file_agent_private_display_v1_service_proto_rawDesc)))
	})
	return file_agent_private_display_v1_service_proto_rawDescData
}

var file_agent_private_display_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_agent_private_display_v1_service_proto_goTypes = []any{
	(*ListRequest)(nil),        // 0: agent.private.display.v1.ListRequest
	(*ListResponse)(nil),       // 1: agent.private.display.v1.ListResponse
	(*Display)(nil),            // 2: agent.private.display.v1.Display
	(*SetEnabledRequest)(nil),  // 3: agent.private.display.v1.SetEnabledRequest
	(*SetEnabledResponse)(nil), // 4: agent.private.display.v1.SetEnabledResponse
}
var file_agent_private_display_v1_service_proto_depIdxs = []int32{
	2, // 0: agent.private.display.v1.ListResponse.displays:type_name -> agent.private.display.v1.Display
	0, // 1: agent.private.display.v1.PrivateDisplayService.List:input_type -> agent.private.display.v1.ListRequest
	3, // 2: agent.private.display.v1.PrivateDisplayService.SetEnabled:input_type -> agent.private.display.v1.SetEnabledRequest
	1, // 3: agent.private.display.v1.PrivateDisplayService.List:output_type -> agent.private.display.v1.ListResponse
	4, // 4: agent.private.display.v1.PrivateDisplayService.SetEnabled:output_type -> agent.private.display.v1.SetEnabledResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_agent_private_display_v1_service_proto_init() }
func file_agent_private_display_v1_service_proto_init() {
	if File_agent_private_display_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_private_display_v1_service_proto_rawDesc), len(file_agent_private_display_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_private_display_v1_service_proto_goTypes,
		DependencyIndexes: file_agent_private_display_v1_service_proto_depIdxs,
		MessageInfos:      file_agent_private_display_v1_service_proto_msgTypes,
	}.Build()
	File_agent_private_display_v1_service_proto = out.File
	file_agent_private_display_v1_service_proto_goTypes = nil
	file_agent_private_display_v1_service_proto_depIdxs = nil
}
